USE opendatasus;
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'bronze_sindrome_gripal')
BEGIN
    CREATE TABLE dbo.bronze_sindrome_gripal (
        sourceId VARCHAR(MAX) NULL,
        origem VARCHAR(MAX) NULL,
        estado VARCHAR(MAX) NULL,
        estadoIBGE VARCHAR(MAX) NULL,
        municipio VARCHAR(MAX) NULL,
        municipioIBGE VARCHAR(MAX) NULL,
        estadoNotificacao VARCHAR(MAX) NULL,
        estadoNotificacaoIBGE VARCHAR(MAX) NULL,
        municipioNotificacao VARCHAR(MAX) NULL,
        municipioNotificacaoIBGE VARCHAR(MAX) NULL,
        sexo VARCHAR(MAX) NULL,
        idade VARCHAR(MAX) NULL,
        racaCor VARCHAR(MAX) NULL,
        profissionalSaude VARCHAR(MAX) NULL,
        profissionalSeguranca VARCHAR(MAX) NULL,
        cbo VARCHAR(MAX) NULL,
        sintomas VARCHAR(MAX) NULL,
        outrosSintomas VARCHAR(MAX) NULL,
        condicoes VARCHAR(MAX) NULL,
        outrasCondicoes VARCHAR(MAX) NULL,
        evolucaoCaso VARCHAR(MAX) NULL,
        classificacaoFinal VARCHAR(MAX) NULL,
        dataNotificacao VARCHAR(MAX) NULL,
        dataInicioSintomas VARCHAR(MAX) NULL,
        dataEncerramento VARCHAR(MAX) NULL,
        dataPrimeiraDose VARCHAR(MAX) NULL,
        dataSegundaDose VARCHAR(MAX) NULL,
        totalTestesRealizados VARCHAR(MAX) NULL,
        codigoEstrategiaCovid VARCHAR(MAX) NULL,
        codigoRecebeuVacina VARCHAR(MAX) NULL,
        codigoDosesVacina VARCHAR(MAX) NULL,
        codigoLaboratorioPrimeiraDose VARCHAR(MAX) NULL,
        codigoLaboratorioSegundaDose VARCHAR(MAX) NULL,
        lotePrimeiraDose VARCHAR(MAX) NULL,
        loteSegundaDose VARCHAR(MAX) NULL,
        codigoContemComunidadeTradicional VARCHAR(MAX) NULL,
        codigoBuscaAtivaAssintomatico VARCHAR(MAX) NULL,
        outroBuscaAtivaAssintomatico VARCHAR(MAX) NULL,
        codigoTriagemPopulacaoEspecifica VARCHAR(MAX) NULL,
        outroTriagemPopulacaoEspecifica VARCHAR(MAX) NULL,
        codigoLocalRealizacaoTestagem VARCHAR(MAX) NULL,
        outroLocalRealizacaoTestagem VARCHAR(MAX) NULL,
        codigoEstadoTeste1 VARCHAR(MAX) NULL,
        codigoTipoTeste1 VARCHAR(MAX) NULL,
        codigoFabricanteTeste1 VARCHAR(MAX) NULL,
        codigoResultadoTeste1 VARCHAR(MAX) NULL,
        dataColetaTeste1 VARCHAR(MAX) NULL,
        codigoEstadoTeste2 VARCHAR(MAX) NULL,
        codigoTipoTeste2 VARCHAR(MAX) NULL,
        codigoFabricanteTeste2 VARCHAR(MAX) NULL,
        codigoResultadoTeste2 VARCHAR(MAX) NULL,
        dataColetaTeste2 VARCHAR(MAX) NULL,
        codigoEstadoTeste3 VARCHAR(MAX) NULL,
        codigoTipoTeste3 VARCHAR(MAX) NULL,
        codigoFabricanteTeste3 VARCHAR(MAX) NULL,
        codigoResultadoTeste3 VARCHAR(MAX) NULL,
        dataColetaTeste3 VARCHAR(MAX) NULL,
        codigoEstadoTeste4 VARCHAR(MAX) NULL,
        codigoTipoTeste4 VARCHAR(MAX) NULL,
        codigoFabricanteTeste4 VARCHAR(MAX) NULL,
        codigoResultadoTeste4 VARCHAR(MAX) NULL,
        dataColetaTeste4 VARCHAR(MAX) NULL,
        isExcluido VARCHAR(MAX) NULL,
        isValidado VARCHAR(MAX) NULL
    );
END;
GO